# Generated by Django 3.2.7 on 2021-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lang_type',
            field=models.CharField(blank=True, choices=[('py', 'Python'), ('js', 'Javascript'), ('css', 'CSS'), ('html', 'HTML')], max_length=50),
        ),
    ]
