# Generated by Django 3.2.7 on 2021-10-21 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, '100文字以内で入力してください')]),
        ),
    ]
